version: '3.8'

services:
  tiktok-bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - douyin-api
    volumes:
      - ./config/config.yaml:/app/config.yaml
    restart: unless-stopped

  douyin-api:
    image: evil0ctal/douyin_tiktok_download_api:latest
    restart: unless-stopped
